"""
Central registry of all project-wide constants.

Rule: NO magic numbers or hardcoded strings anywhere else in the codebase.
Every tuneable value lives here with a clear name and unit comment.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Steam process names
# ---------------------------------------------------------------------------

STEAM_PROCESS_NAMES: frozenset[str] = frozenset({"steam.exe", "steamwebhelper.exe"})

# ---------------------------------------------------------------------------
# TF2 process names and Steam App ID
# ---------------------------------------------------------------------------

TF2_APP_ID: str = "440"

TF2_PROCESS_NAMES: frozenset[str] = frozenset(
    {"hl2.exe", "tf_win64.exe"}  # 32-bit and 64-bit builds
)

# ---------------------------------------------------------------------------
# TF2 launch options
# ---------------------------------------------------------------------------

TF2_LAUNCH_OPTIONS: list[str] = [
    "-novid",
    "-nojoy",
    "-nosteamcontroller",
    "-nohltv",
    "-particles", "1",
    "-console",
    "-sw",
    "-w", "800",
    "-h", "600",
    "-noborder",
    "-low",
    "-nosound",
    "-condebug",             # write console output to console.log
    "+mat_queue_mode", "0",
    "+r_renderoverlayfragment", "0",
]

# ---------------------------------------------------------------------------
# TF2 autoexec.cfg template
# ---------------------------------------------------------------------------

AUTOEXEC_TEMPLATE: str = """\
// Auto-generated by TF2 Idle Farmer — do not edit manually
fps_max 20
mat_picmip 4
r_drawparticles 0
cl_detaildist 0
cl_detailfade 0
r_shadowrendertotexture 0
mat_reduceparticles 1
nosound 1
connect {server}
"""

# ---------------------------------------------------------------------------
# Steam launch flags
# ---------------------------------------------------------------------------

# Minimised to tray, no splash screen
STEAM_FLAG_SILENT: str = "-silent"

# Disable the newer React-based login UI (older flow is more
# automation-friendly on some Steam versions)
STEAM_FLAG_NO_REACT_LOGIN: str = "-noreactlogin"

STEAM_FLAG_LOGIN: str = "-login"

# URI used to request a graceful shutdown
STEAM_EXIT_URI: str = "steam://exit"

# ---------------------------------------------------------------------------
# Steam shutdown / force-kill
# ---------------------------------------------------------------------------

# Seconds to wait for Steam to exit gracefully before force-killing
STEAM_GRACEFUL_EXIT_TIMEOUT_SEC: int = 30

# Poll interval while waiting for Steam to exit (seconds)
STEAM_EXIT_POLL_INTERVAL_SEC: int = 2

# ---------------------------------------------------------------------------
# Steam wait / stabilisation
# ---------------------------------------------------------------------------

# Poll interval while waiting for Steam process to appear (seconds)
STEAM_START_POLL_INTERVAL_SEC: int = 3

# Fixed extra wait after the Steam process is detected so the client can
# finish authenticating before TF2 is launched (seconds).
# Increase to 25-30 on slow machines or HDD.
STEAM_STABILISE_SEC: int = 15

# ---------------------------------------------------------------------------
# TF2 wait
# ---------------------------------------------------------------------------

# Poll interval while waiting for TF2 process to appear (seconds)
TF2_START_POLL_INTERVAL_SEC: int = 4

# ---------------------------------------------------------------------------
# Human-behaviour knobs
# ---------------------------------------------------------------------------

# Probability that *some* micro-action is performed each idle wakeup (0–1)
IDLE_ACTION_PROBABILITY: float = 0.40

# Minimum / maximum idle sleep window per wakeup cycle (seconds)
IDLE_SLEEP_MIN_SEC: float = 180.0   # 3 min
IDLE_SLEEP_MAX_SEC: float = 600.0   # 10 min

# ---------------------------------------------------------------------------
# Bézier mouse movement
# ---------------------------------------------------------------------------

BEZIER_STEPS_MIN: int = 20
BEZIER_STEPS_MAX: int = 40

# Seconds between each individual step of the Bézier curve
BEZIER_STEP_DELAY_MIN_SEC: float = 0.010
BEZIER_STEP_DELAY_MAX_SEC: float = 0.030

# Screen-edge margin so the cursor never lands in a corner (pixels)
MOUSE_SCREEN_MARGIN_PX: int = 50
MOUSE_CTRL_POINT_MARGIN_PX: int = 100

# ---------------------------------------------------------------------------
# MOTD dismissal
# ---------------------------------------------------------------------------

# Number of key-sequence repetitions when dismissing the server MOTD.
# 8 covers servers with up to 3-4 stacked MOTD panels.
MOTD_DISMISS_ATTEMPTS: int = 8

# Seconds between each MOTD dismissal attempt
MOTD_DISMISS_INTERVAL_SEC: float = 4.0

# Keys sent per attempt (Enter × N, then Space, then F)
MOTD_ENTER_REPEAT: int = 4

# Delay between individual key presses within one attempt (seconds)
MOTD_KEY_DELAY_SEC: float = 0.20

# Keys used as fallbacks for non-standard MOTD bindings
MOTD_FALLBACK_KEYS: list[str] = ["space", "f"]

# ---------------------------------------------------------------------------
# Item-drop popup dismissal
# ---------------------------------------------------------------------------

# How often to check for (and dismiss) item-drop notifications during idle.
# Set to 0 to disable.
DROP_DISMISS_INTERVAL_SEC: int = 120   # every ~2 min

# Keys sent to close the drop popup
DROP_DISMISS_KEYS: list[str] = ["return", "escape"]

# Delay between drop-dismiss keys (seconds)
DROP_DISMISS_KEY_DELAY_SEC: float = 0.15

# ---------------------------------------------------------------------------
# AFK-prevention key presses
# ---------------------------------------------------------------------------

# Harmless keys sent to the TF2 window to prevent AFK detection
AFK_SAFE_KEYS: list[str] = ["escape", "f5"]

# ---------------------------------------------------------------------------
# Item-drop notification popup dismissal (post-session cleanup)
# ---------------------------------------------------------------------------

# Seconds after TF2 shutdown before moving to the next account (best-effort
# fallback — the main pause comes from settings.toml)
CLEANUP_WAIT_MIN_SEC: float = 5.0
CLEANUP_WAIT_MAX_SEC: float = 10.0

# ---------------------------------------------------------------------------
# Session startup waits
# ---------------------------------------------------------------------------

# Wait after TF2 starts for map load + autoexec connect (seconds)
SESSION_MAP_LOAD_WAIT_MIN_SEC: float = 20.0
SESSION_MAP_LOAD_WAIT_MAX_SEC: float = 40.0

# ---------------------------------------------------------------------------
# Drop tracking / console.log parsing
# ---------------------------------------------------------------------------

# Poll interval for the live console.log watcher (seconds)
CONSOLE_LOG_POLL_INTERVAL_SEC: float = 10.0

# Regex patterns for item-drop lines written by TF2.
# Both "found" and "received" variants are matched for robustness.
# Quotes around the item name (some server configs) are stripped.
DROP_LOG_PATTERNS: list[str] = [
    r'You have (?:found|received) a "?(.+?)"?!',
]

# ---------------------------------------------------------------------------
# Drop history JSON
# ---------------------------------------------------------------------------

# ISO-8601 time resolution stored in drops.json
DROPS_TIMESTAMP_TIMESPEC: str = "seconds"

# ---------------------------------------------------------------------------
# Logger
# ---------------------------------------------------------------------------

LOG_FORMAT: str = "[%(asctime)s] [%(levelname)-5s] %(message)s"
LOG_DATE_FORMAT: str = "%Y-%m-%d %H:%M:%S"

# Rotate when the log file reaches this size (bytes)
LOG_MAX_BYTES: int = 5 * 1024 * 1024   # 5 MB

# Number of rotated backups to keep
LOG_BACKUP_COUNT: int = 3

# ---------------------------------------------------------------------------
# Steam warmup fallback defaults
# (used when the keys are absent from settings.toml)
# ---------------------------------------------------------------------------

STEAM_WARMUP_MIN_SEC_DEFAULT: int = 30
STEAM_WARMUP_MAX_SEC_DEFAULT: int = 60

# ---------------------------------------------------------------------------
# Unit conversion
# ---------------------------------------------------------------------------

SECONDS_PER_MINUTE: int = 60

# ---------------------------------------------------------------------------
# Scheduler
# ---------------------------------------------------------------------------

# Day and time for the weekly farming run
SCHEDULE_DAY: str = "monday"
SCHEDULE_TIME: str = "09:00"

# How often the scheduler wakes up to check for pending jobs (seconds)
SCHEDULE_POLL_SEC: int = 60

# ---------------------------------------------------------------------------
# Weekly summary window
# ---------------------------------------------------------------------------

WEEKLY_SUMMARY_DAYS: int = 7